### ISSUE TITLE
Result code contains unnecessary semicolon

### ISSUE THREAD

**Issue by kimown** [square/babel-codemod#24] opened 2017-06-09 00:58 UTC
After transforming, the generate code contains unnecessary semicolon, here is my code.

source code:
```js
function square (n) {
  return n * n
}
```
plugin:
```js
module.exports = function () {
  return {
    visitor: {
      FunctionDeclaration (path) {
        path.scope.rename('n', 'x')
      }
    }
  }
}
```

result:
```js
function square (x) {
  return x * x;
}
```
the result code is what I want, but in return statement contains an unnecessary semicolon, can we    
 rewrite source code without semicolons.

**Comment by eventualbuddha** [comment] 2017-06-20 15:04
Here's an [astexplorer snippet](https://astexplorer.net/#/gist/ceede66ae8fec6f11b0f83b66de35140/f887f2cf85f1b3023cec72bde64e4fa5f604b4cd) that reproduces the problem. My guess is that this change would need to be made in recast. cc @benjamn @hzoo

**Comment by NickTomlin** [comment] 2017-10-13 18:21
Just ran into this as well. It looks like this has been discussed in https://github.com/benjamn/recast/issues/140 and is a bit of a bear due to potential gotchas with ASI. I don't have the time or expertise to submit a PR to do anything about that but if anyone does feel free to!

Resolving this for me was as simple `standard --fix` after running my codemod (`prettier` would work great too). That's not necessarily ideal for codemod consumers but also not the end of the world.

**Comment by eventualbuddha** [comment] 2018-04-18 14:53
For anyone who stumbles on this, if you happen to already use `prettier` then you might want to use `--printer prettier` to use prettier as a post-processor for your codemod.

**Closed by eventualbuddha** 2018-04-18 14:53 UTC
Labels: bug
